### ISSUE TITLE
We are looking forward to the update oauth2-oidc-sdk:8.0 or higher

### ISSUE THREAD

**Issue by aukhatov** [AzureAD/microsoft-authentication-library-for-java#342]
Hello guys!
@sangonzal we've started using the library and faced an issue with some transitive dependencies.
Specially with `com.nimbusds:oauth2-oidc-sdk:7.4`, there use `com.sun.mail:javax.mail:1.6.1`.
And we can't solve this issue on our side. But there is good news, they've removed the dependency on 8.0.x version or higher.

Is it possible to update the version of the dependency for the next release? Please 😊 
What is the estimated time of arrival?

**Comment by Avery-Dunn** [comment]
Hello @aukhatov : We'll be upgrading this dependency in the next release, likely by the end of this week or next week. 

We had another issue with that dependency that was fixed in version 1.8.1 of the library (see https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/335), so if you aren't already using it try using 1.8.1 (I think your issue is different and will still exist in 1.8.1, but it's worth a shot).

**Comment by aukhatov** [comment]
@Avery-Dunn Actually we use version 1.8.1, but the issue still exists 😞 
This is fantastic news, I'm waiting for the next release 🙌
